[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200








